import random

# List of strings
strings_list = ["Aardonyx",
"Abelisaurus",
"Achelousaurus",
"Achillobator",
"Acrocanthosaurus",
"Aegyptosaurus",
"Afrovenator",
"Agilisaurus",
"Alamosaurus",
"Albertaceratops",
"Albertosaurus",
"Alectrosaurus",
"Alioramus",
"Allosaurus",
"Alvarezsaurus",
"Amargasaurus",
"Ammosaurus",
"Ampelosaurus",
"Amygdalodon",
"Anchiceratops",
"Anchisaurus",
"Ankylosaurus",
"Anserimimus",
"Antarctosaurus",
"Apatosaurus",
"Aragosaurus",
"Aralosaurus",
"Archaeoceratops",
"Archaeopteryx",
"Archaeornitho-mimus",
"Argentinosaurus",
"Arrhinoceratops",
"Atlascopcosaurus",
"Aucasaurus",
"Austrosaurus",
"Avaceratops",
"Avimimus",
"Bactrosaurus",
"Bagaceratops",
"Bambiraptor",
"Barapasaurus",
"Barosaurus",
"Baryonyx",
"Becklespinax",
"Beipiaosaurus",
"Bellusaurus",
"Borogovia",
"Brachiosaurus",
"Brachylopho-saurus",
"Brachytrachelopan",
"Buitreraptor",
"Camarasaurus",
"Camptosaurus",
"Carcharodonto-saurus",
"Carnotaurus",
"Caudipteryx",
"Cedarpelta",
"Centrosaurus",
"Ceratosaurus",
"Cetiosauriscus",
"Cetiosaurus",
"Chaoyangsaurus",
"Chasmosaurus",
"Chindesaurus",
"Chinshakiango-saurus",
"Chirostenotes",
"Chubutisaurus",
"Chungkingosaurus",
"Citipati",
"Coelophysis",
"Coelurus",
"Coloradisaurus",
"Compsognathus",
"Conchoraptor",
"Confuciusornis"

]

# Function to display a random string from the list
def display_random_string():
    random_string = random.choice(strings_list)
    print("Dino of The Day: {}".format(random_string))

# Display a random string
display_random_string()
